google:
  maps:
    api:
      key: addnewapikey
logging:
  level:
    org:
      springframework:
        security: trace
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/core_api
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
  data:
    redis:
      host: localhost
      password: foobared
      port: 6379

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: https://login.microsoftonline.com/d132f480-130a-4dd3-8d67-3b0b856bb69e/v2.0
            jwk-set-uri: https://login.microsoftonline.com/d132f480-130a-4dd3-8d67-3b0b856bb69e/discovery/v2.0/keys